### ISSUE TITLE
BUG: Functions parsing InLoadOrderModuleList have wrong ending condition

### ISSUE THREAD

**Issue by ladislav-zezula** [kevoreilly/capemon#13]
1) The structure [LDR_MODULE](https://github.com/kevoreilly/capemon/blob/21ac0e0a6e809e6657368796e5c8c776059e3722/ntapi.h#L463) should be renamed to LDR_DATA_TABLE_ENTRY. This is the name under which the structure is publicky known

2) These functions, parsing the `InLoadOrderModuleList` have their ending condition wrong and are touching random data via `mod->BaseAddress`.

- add_all_dlls_to_dll_ranges
- convert_address_to_dll_name_and_offset
- hide_module_from_peb
- get_basename_of_module

I'll prepare pull request for this.

**Comment by kevoreilly** [comment]
Thank you :heart:
