### ISSUE TITLE
Hook for RtlDispatchException is not implemented well

### ISSUE THREAD

**Issue by ladislav-zezula** [kevoreilly/capemon#20]
In Windows NT, the function `RtlDispatchException` is responsible for sending the exception to each registered frame, until it finds one that handles the exception. After this function is done, it will not return to the caller, but will pass control directly to the exception handler.

At [hook_process.c(1049)](https://github.com/kevoreilly/capemon/blob/330c43d3a7669391756aa33e03e089cf6c9b0ed9/hook_process.c#L1049), there is a construction that attempts to handle exception. The `log_flush` call that follows up after, is potentially never called.

So, to fix this problem:
1) Either put the `log_flush` call before the call to `CAPEExceptionDispatcher`
2) or mark the entire `New_RtlDispatchException` as `HOOKDEF_NOTAIL`, which will auto-call the original function after the hook is done.

The problem caused by the current state is the following. Let's have a simple program:
```
static ULONG ExceptionHandler(LPEXCEPTION_POINTERS ExceptionPointers)
{
    PEXCEPTION_RECORD ExceptionRecord = ExceptionPointers->ExceptionRecord;
    PCONTEXT pContext = ExceptionPointers->ContextRecord;

    printf("Exception %08X at %p\n", ExceptionRecord->ExceptionCode, ExceptionRecord->ExceptionAddress);
    printf("Trying to skip the instruction ...\n");

#ifdef _WIN64
    pContext->Rip += GetInstructionLength((unsigned char *)ExceptionRecord->ExceptionAddress, 64);
#else
    pContext->Eip += GetInstructionLength((unsigned char *)ExceptionRecord->ExceptionAddress, 32);
#endif

    return EXCEPTION_EXECUTE_HANDLER;
}

//int WINAPI _tWinMain(HINSTANCE, HINSTANCE, LPTSTR, int)
void _cdecl main()
{
    printf("Hello, World, I am a test program for cuckoo/CAPE.\n\n");
    //printf("Capemon base address: %p\n", GetModuleHandle(_T("capemon_x64.dll")));

    printf("Before __try\n");
    //__debugbreak();

    __try
    {
        printf("Inside __try\n");
        *(char *)0 = 0;
        printf("After exception\n");
    }
    __except(ExceptionHandler(GetExceptionInformation()))
    {
        printf("Inside __except\n");
    }

    printf("After __except\n");

    printf("\nTestprogram exiting ...\n");
    _getch();
}
```

When 64-bit version executed in CAPE, it only gives the following console output:

```
Hello, World, I am a test program for cuckoo/CAPE.
 
* (0): Before __try
* (1): Inside __try
* (4): Inside __except
* (5): After __except
 
Testprogram exiting ...
```

**Comment by ladislav-zezula** [comment]
The compiled 64-bit Test.exe program is here:
[Test.zip](https://github.com/kevoreilly/capemon/files/6701435/Test.zip)

**Comment by kevoreilly** [comment]
Thank you! I really appreciate these reports. Fixed in this repo - I will publish new monitors to the CAPE repo shortly 👍
