### ISSUE TITLE
How to compile it properly

### ISSUE THREAD

**Issue by 3ntr0phy** [kevoreilly/capemon#30]
Hi, 
I am noticing a huge difference between the capemon I compile and the one downloaded from CAPEv2 repo.
Could you please share how you compile the libraries ?
Debug or Release?
I am using both VS2017 and VS2019 and with this release of capemon I keep having the same issue.
Thank you

**Comment by 3ntr0phy** [comment]
Also which Windows version are you using...

**Comment by kevoreilly** [comment]
When you say huge difference, what do you mean? Does it function?

It's compiled release build in VS2017 on Win10 but I don't think the OS matters. The vcxproj indicates it's for VS2017 with the line: <Project DefaultTargets="Build" ToolsVersion="15.0" ...

**Comment by 3ntr0phy** [comment]
No it does not function properly unfortunately, when I compile it it keeps crashing during the analyses.

**Comment by doomedraven** [comment]
im compiling that on vs2017 on win7x32 without problems, ensure the toolset version

**Comment by 3ntr0phy** [comment]
Thank you
I had to downgrade to VS2017 15.0, was using 15.9.
This was probably the issue.

**Comment by doomedraven** [comment]
glad that you solved that

**Comment by kevoreilly** [comment]
Glad it's solved, although I am using 15.9.38
