### ISSUE TITLE
Problem in detonation

### ISSUE THREAD

**Issue by simone-co** [kevoreilly/capemon#45]
Hello.
I work in a company that deals with cybersecurity, my colleague and I are also analyzing capemon and we have found some problems in detonation phase with the golang and with edr bypass techniques used by some malware.

Since cape is also used by companies it would be more appropriate not to disclose certain information in public until it is fixed.
@kevoreilly is it possible to contact you privately to discuss how to fix?

Thanks for your attention.

**Comment by kevoreilly** [comment]
Yes can you send a twitter dm to @capesandbox?

**Comment by simone-co** [comment]
@kevoreilly 
I've a problem to send you a DM on Twitter.

**Comment by doomedraven** [comment]
check here you have our emails https://github.com/kevoreilly/CAPEv2/blob/master/pyproject.toml#L5

**Comment by simone-co** [comment]
> check here you have our emails https://github.com/kevoreilly/CAPEv2/blob/master/pyproject.toml#L5

Ok Thanks.
