### ISSUE TITLE
Capemon failed to build with "fatal error LNK1104: cannot open file 'atls.lib' " with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [kevoreilly/capemon#46]
Capemon failed to build with "fatal error LNK1104: cannot open file 'atls.lib' " with MSVC on Windows arm64ec. It can reproduce on latest version on capemon branch. Could you please help look at this issue?

R**epro steps:**

1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/kevoreilly/capemon F:\capemon
3. cd F:\capemon
4. Change "x64" to "ARM64EC" in capemon.sln bson.vcxproj capemon.vcxproj files
5. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.22618.0 /p:PlatformToolset=v142 capemon.sln /t:Rebuild

**Error info:**
`LINK : fatal error LNK1104: cannot open file 'atls.lib' [F:\capemon\capemon.vcxproj]`

**Error log:**
[Capemon_build_LNK1104.log](https://github.com/kevoreilly/capemon/files/9672376/Capemon_build_LNK1104.log)

**Comment by kevoreilly** [comment]
Sorry capemon cannot be compiled for arm, it's Intel only.
