### ISSUE TITLE
[MSVC][permissive-][std:c++latest] Capemon failed to build with msvc due to error C2362 error2440 on Windows

### ISSUE THREAD

**Issue by shizhuoer** [kevoreilly/capemon#47]
Hi all,
Capemon failed to build with msvc due to error C2362 error2440 on Windows. Could you please help look at this issue?

**Environment:**
Windows: windows server 2019
VS: 2019

**Repro steps:**
1.open VS2019 x64 tools command
2.git clone https://github.com/kevoreilly/capemon F:\gitP\kevoreilly\capemon
3.cd F:\gitP\kevoreilly\capemon
4.mkdir build_amd64 & cd F:\gitP\kevoreilly\capemonl\build_amd64
5.set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 & set _CL_= /permissive-
6.msbuild /m /p:Platform=x64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:PlatformToolset=v142 capemon.sln /t:Rebuild

**Error info:**
 F:\gitP\kevoreilly\capemon\CAPE\AmsiDumper.cpp(163,13): error C2362: initialization of 'hr' is skipped by 'got
       o error' [F:\gitP\kevoreilly\capemon\capemon.vcxproj]
         F:\gitP\kevoreilly\capemon\CAPE\Scylla\IATReferenceScan.cpp(425,15): error C2440: 'initializing': cannot conve
       rt from 'const char [2]' to 'CHAR *' [F:\gitP\kevoreilly\capemon\capemon.vcxproj]
         F:\gitP\kevoreilly\capemon\CAPE\Scylla\IATReferenceScan.cpp(429,11): error C2440: '=': cannot convert from 'co
       nst char [5]' to 'CHAR *' [F:\gitP\kevoreilly\capemon\capemon.vcxproj]
         F:\gitP\kevoreilly\capemon\CAPE\Scylla\IATReferenceScan.cpp(433,11): error C2440: '=': cannot convert from 'co
       nst char [4]' to 'CHAR *' [F:\gitP\kevoreilly\capemon\capemon.vcxproj]
         F:\gitP\kevoreilly\capemon\CAPE\Scylla\IATReferenceScan.cpp(437,11): error C2440: '=': cannot convert from 'co
       nst char [4]' to 'CHAR *' [F:\gitP\kevoreilly\capemon\capemon.vcxproj]
         F:\gitP\kevoreilly\capemon\CAPE\Scylla\IATReferenceScan.cpp(441,11): error C2440: '=': cannot convert from 'co
       nst char [5]' to 'CHAR *' [F:\gitP\kevoreilly\capemon\capemon.vcxproj]
         F:\gitP\kevoreilly\capemon\CAPE\Scylla\IATReferenceScan.cpp(445,11): error C2440: '=': cannot convert from 'co
       nst char [4]' to 'CHAR *' [F:\gitP\kevoreilly\capemon\capemon.vcxproj]

**log**
[build.log](https://github.com/kevoreilly/capemon/files/9762264/build.log)

**Comment by kevoreilly** [comment]
I'm sorry but I'm afraid capemon is VS2017 only.
