### ISSUE TITLE
Crash due to wrong prototype for NtAllocateVirtualMemoryEx

### ISSUE THREAD

**Issue by michaelweiser** [kevoreilly/capemon#52]
I've been seeing crashes in the `NtAllocateVirtualMemoryEx` hook as can be seen here:
![virtualallocex-access-violation](https://user-images.githubusercontent.com/1473703/209335162-e9ae2999-d665-45a2-8dea-5d7d3fe330d1.png)
(please excuse the German UI, the debug machine was not mine)

It looked like a call-by-value with a large operand to me and pointed me towards the `__inout  MEM_EXTENDED_PARAMETER Parameters` argument to the function. Since I've never seen such a large structure being passed by value in any API I dug a bit and found this alternative usage much more in line with my experience: dotnet/runtime#12779

After changing the prototype to use a pointer like so, the crashes went away:
``` C
	__inout  MEM_EXTENDED_PARAMETER *Parameters,
```

See also: https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc2

This also jives with `Parameters` being an array of `MEM_EXTENDED_PARAMETER`s defined by last argument `ParameterCount`.

**Comment by michaelweiser** [comment]
The hook for `NtMapViewOfSectionEx` might also be affected by this.

**Comment by kevoreilly** [comment]
Thanks a lot!
