### ISSUE TITLE
InjectDllViaIAT failed in Windows 10

### ISSUE THREAD

**Issue by oalieno** [kevoreilly/capemon#53]
https://capesandbox.com/analysis/352187/
This Lockbit sample has both **Import Directory** and **Import Address Table (IAT)** empty.

![image](https://user-images.githubusercontent.com/18167730/212029169-463aee9a-f724-49ac-869f-2629d91d0133.png)

loader.exe will use InjectDllViaIAT to inject the capemon.dll into process. 

https://github.com/kevoreilly/capemon/blob/95ed91f578fb1e7ffbd4231f7836c22d657c4873/loader/loader/Loader.c#L1081-L1089

Because both Import Directory and IAT is 0, `NtHeader.IAT_DIRECTORY.VirtualAddress = ImportsSection.VirtualAddress;` this line will do nothing and set IAT to 0 again. Now, Only Import Directory will have valid value and IAT set to 0. According to my test results, this is fine in Windows 7, but it fails to load the capemon in Windows 10.

A quick fix is to set IAT to the FirstThunk we created. ( or just disable InjectDllViaIAT )

```diff
diff --git a/loader/loader/Loader.c b/loader/loader/Loader.c
index 96478bb..e73f4b5 100644
--- a/loader/loader/Loader.c
+++ b/loader/loader/Loader.c
@@ -1081,11 +1081,17 @@ rebase:
        // If IAT zero, set it to section that contains original import table to prevent LdrpSnapIAT failure
        if (NtHeader.IAT_DIRECTORY.VirtualAddress == 0)
        {
-               NtHeader.IAT_DIRECTORY.VirtualAddress = ImportsSection.VirtualAddress;
-               if (ImportsSection.Misc.VirtualSize)
-                       NtHeader.IAT_DIRECTORY.Size = ImportsSection.Misc.VirtualSize;
-               else
-                       NtHeader.IAT_DIRECTORY.Size = ImportsSection.SizeOfRawData;
+               if (ImportsSection.VirtualAddress == 0) {
+                       NtHeader.IAT_DIRECTORY.VirtualAddress = pImageDescriptor->FirstThunk;
+                       NtHeader.IAT_DIRECTORY.Size = 8;
+               }
+               else {
+                       NtHeader.IAT_DIRECTORY.VirtualAddress = ImportsSection.VirtualAddress;
+                       if (ImportsSection.Misc.VirtualSize)
+                               NtHeader.IAT_DIRECTORY.Size = ImportsSection.Misc.VirtualSize;
+                       else
+                               NtHeader.IAT_DIRECTORY.Size = ImportsSection.SizeOfRawData;
+               }
        }

        // Now set the import table directory entry to point to the new table
```

I will open a pull request if this fix is ok.

**Comment by kevoreilly** [comment]
Thank you! I was not aware of this difference in Windows 10, I am very grateful not only that you brought it to my attention, but also provided a solution.

No need to create a PR - I have added your fix which is great. The only change I made is to put `sizeof(IMAGE_THUNK_DATAXX)` instead of just hard-coding the size `8`.

Much appreciated.
