### ISSUE TITLE
CAPEv2 cannot handle with GoLang go-clr-based droppers

### ISSUE THREAD

**Issue by yevhenprotsenko** [kevoreilly/capemon#55]
[GoLang_ServHelper.zip](https://github.com/kevoreilly/CAPEv2/files/7774340/GoLang_ServHelper.zip)

The password is infected. The final payload should be ServHelper RAT. The dropper should load the .NET ServHelper dropper into memory to execute it.

**Comment by kevoreilly** [comment]
Thanks - it's a well known issue that golang samples do not work well in cape. I'm actively researching the issues which are related to golang's use of its own stack which causes issues with api hooking. Watch this space.

**Comment by kevoreilly** [comment]
I am happy to say that with the sands of time capemon has improved to the point that when I test on today's version, these samples appear to detonate perfectly with the .NET ServHelper dropper being captured as well as another stage in payloads.

![image](https://github.com/kevoreilly/capemon/assets/22219888/f6cfecf9-c9e5-4c68-a294-3e57caa44ded)

So this issue and the issues with golang binaries more generally seem to be solved. Please let me know if there are any further issues that come to light.
