### ISSUE TITLE
Yara.h not found

### ISSUE THREAD

**Issue by 3ntr0phy** [kevoreilly/capemon#7]
I am importing the actual VS Project but it seems that some dependencies are broken, are you still working on it? 
Thank you

**Comment by kevoreilly** [comment]
Hi Jacoppy - please try updating to the latest as I have recently solved a problem preventing compiling from a fresh clone. I have just tested the latest push does compile from a fresh clone for me.

**Comment by kevoreilly** [comment]
Closing as fixed

**Comment by 3ntr0phy** [comment]
Hey, it's me again.
I have the same issue again, just cloned the repo, imported in VS 2019 and still Yara.h not found.
Am I missing something?

**Comment by kevoreilly** [comment]
Yes indeed! capemon is built in VS2017!

**Comment by 3ntr0phy** [comment]
I solved it!
It seems that all the external configuration for external libraries was gone while importing the project, I also tried with VS 2017.
While setting everything manually solved the issues.
Cheers

**Comment by kevoreilly** [comment]
Let me know if you successfully build in 2019

**Comment by 3ntr0phy** [comment]
Yup it compiles but it outputs some warnings :
```>libyara32.lib(a_bitstr.obj) : warning LNK4099: PDB 'ossl_static.pdb' was not found with 'libyara32.lib(a_bitstr.obj)' or at 'C:\Users\John\Documents\DOMINIK_SYNC_CAPEMON\capemon\Debug\ossl_static.pdb'; linking object as if no debug info
3>libyara32.lib(aria.obj) : warning LNK4099: PDB 'ossl_static.pdb' was not found with 'libyara32.lib(aria.obj)' or at 'C:\Users\John\Documents\DOMINIK_SYNC_CAPEMON\capemon\Debug\ossl_static.pdb'; linking object as if no debug info
3>libyara32.lib(aes_wrap.obj) : warning LNK4099: PDB 'ossl_static.pdb' was not found with 'libyara32.lib(aes_wrap.obj)' or at 'C:\Users\John\Documents\DOMINIK_SYNC_CAPEMON\capemon\Debug\ossl_static.pdb'; linking object as if no debug info
3>libyara32.lib(aes_core.obj) : warning LNK4099: PDB 'ossl_static.pdb' was not found with 'libyara32.lib(aes_core.obj)' or at 'C:\Users\John\Documents\DOMINIK_SYNC_CAPEMON\capemon\Debug\ossl_static.pdb'; linking object as if no debug info
3>libyara32.lib(aes_cbc.obj) : warning LNK4099: PDB 'ossl_static.pdb' was not found with 'libyara32.lib(aes_cbc.obj)' or at 'C:\Users\John\Documents\DOMINIK_SYNC_CAPEMON\capemon\Debug\ossl_static.pdb'; linking object as if no debug info```



Digging into those now

**Comment by kevoreilly** [comment]
Let me know if it works - linking without debug info may be no problem

**Comment by 3ntr0phy** [comment]
it works buddy

**Comment by kevoreilly** [comment]
That sounds like good news! Maybe I should look at upgrading. Thanks for the feedback.
